

spring:
  config:
    import:
      - classpath:application-secret_common.yml
      - classpath:application-secret_dev.yml
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc.batch_size: 1000



logging:
  level:
    #root: debug
    org:
      springframework:
        orm:
          jpa: DEBUG

      hibernate:
        type:
          descriptor:
            sql: trace