spring:
  config:
    import:
      - classpath:application_common.yml
client:
  origin: https://ohs.kr

server:
  servlet:
    session:
      cookie:
        domain: ohs.kr # sub1.ohs.kr, sub2.ohs.kr 등 모든 하위 도메인에서 세션 쿠키가 유효
        secure: true
        same-site: none

logging:
  config: classpath:logback-prod.xml

