server:
  port: 443

spring:
  config:
    import: classpath:application-secret.yml

  #JPA
  jpa:
    show_sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
     hibernate:
        jdbc.batch_size: 1000
        #order_inserts: true
        #order_updates: true
        format_sql: true
        #show_sql: true
        #highlight_sql: true
        #use_sql_comments: true
    #defer-datasource-initialization: true
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG

      hibernate:
        type:
          descriptor:
            sql: trace


