server:
  port: 443






spring:
  config:
    import:
    - classpath:application-secret_common.yml
    - classpath:application-secret.yml
  flyway:
    enabled: true
    baseline-on-migrate: false # 최초 적용시에만 true로 설정, 적용 후에는 false로 바꾸기.
    baseline-version: 1

  #JPA
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc.batch_size: 1000
        #order_inserts: true
        #order_updates: true
        #format_sql: true
        #show_sql: true
        #highlight_sql: true
        #use_sql_comments: true
    #defer-datasource-initialization: true



