server:
  port: 443

spring:
  config:
    import: classpath:application-secret.yml

  #JPA
  jpa:
    show_sql: true
    #open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
     hibernate:
        format_sql: true
        #show_sql: true
        #highlight_sql: true
    #defer-datasource-initialization: true
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
      hibernate:
        type:
          descriptor:
            sql: trace
      #springframework:
      #  security: DEBUG

