

spring:
  config:
    import:
      - classpath:application_common.yml
  jpa:
    show_sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: http://localhost/login/oauth2/code/kakao
          naver:
            redirect-uri: http://localhost/login/oauth2/code/naver
          google:
            redirect-uri: http://localhost/login/oauth2/code/google

client:
  origin: http://localhost:3000

server:
  servlet:
    session:
      cookie:
        domain: localhost
        secure: false
        same-site: lax

logging:
  config: classpath:logback-dev.xml