server:
  port: 443

spring:
  config:
    import:
    - classpath:application-secret_common.yml
    - classpath:application-secret.yml

  #JPA
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc.batch_size: 1000
        #order_inserts: true
        #order_updates: true
        #format_sql: true
        #show_sql: true
        #highlight_sql: true
        #use_sql_comments: true
    #defer-datasource-initialization: true



