server:
  port: 443

spring:
  config:
    import: classpath:application-secret.yml

  #JPA
  jpa:
    show_sql: true
    #database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        #show_sql: true
        #highlight_sql: true
    defer-datasource-initialization: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
      springframework:
        security:
          web:
            FilterChainProxy=DEBUG: