server:
  port: 8080

spring:
  config:
    import: classpath:application-secret.yml

  #JPA
  jpa:
    #database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        #show_sql: true
        #highlight_sql: true
    defer-datasource-initialization: true